---
- hosts: web
  remote_user: amr
  become: yes
  vars:
    - dir_name: test
    - myname: amros
    - update: no
  # vars_prompt:
  #   - name: pass
  #     prompt: plz enter your pass
  #     private: yes
  tasks:
      - name: update_cache
        apt:
          update_cache: yes
        when: ansible_facts["os_family"]=="Debian"
  #   - name: install nginx
  #     apt:
  #       name: nginx
  #       state: present
  #   - name: create dir
  #     file:
  #       path: "{{ dir_name }}"
  #       state: directory
  #   - name:
  #     command: "ls {{ dir_name }}"
  #     register: results

  #   - name: print stdout
  #     debug:
  #       var: results.stdout
      - name: copy template
        template:
          src: myconf
          dest: myconf