---
- hosts: web
  remote_user: amr
  become: yes
  tasks:
    - name: update_cache
      apt:
        update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: present