---
- hosts: web
  remote_user: amr
  become: yes
  tasks:
    - name: update_cache
      apt:
        update_cache: yes
    - name: install apache
      apt:
        name: httpd
        state: present